### ISSUE TITLE
Flip up screen on 3d printed remote?

### ISSUE THREAD

**Issue by ThomasDh-C** [RollingGecko/ArduBoardControler#1]
I am thinking of making a board next year and am also going to be making my own remote (based on your software). I was wondering if I understood correctly that the remote is being sent all the data back from the VESC as well - so that I could display speed and miles left (based on watt-hours left and watt-hour usage for the past half mile). I also cannot work out if, like throttle, there could be variable braking power - thinking of a slider pot with a pull back to brake (when going forward)/ reverse (if a button is pressed) and slide forward to accelerate (forward)/ brake (when going backwards and if the same button as above is pressed. These are not really issues but questions!

**Comment by RollingGecko** [comment]
You are right. You get all feedback shown on an oled. Need to add a new page on the wiki ass well. 

At the moment the controll works this way:

I use a 2 axis joystick. Left and right is to flip though different views on the display.
Forward is accelerating. backward is variable breaking. 
One button is used to change direction. Pushing it once is for backwards . Pushing it again is back to forward. Accelerating and breaking remains.
The second button is used for speed control. It will keep the rpm on a constant level as long as you push it.,

Hope that answers all.

Regards

Andy

**Comment by ThomasDh-C** [comment]
Many thanks for the explanation.
