### ISSUE TITLE
Nunchuck issue error

### ISSUE THREAD

**Issue by Fabian287** [RollingGecko/ArduBoardControler#2]
Hallo ich ab dien ArduBoardController nachgebaut hab aber das problem das das Signal ungenau ist also im BLDC Tool sin schwankungen zu erkennen wenn ich den Joystick bewege. Mein kabel von dem poti zum nano hat 0,5 OHm kann das der fehler sein? Auf dem OLED sieht man auch deutlich die Schwankungen.

**Comment by RollingGecko** [comment]
Hi,

Das könnte an den Potis liegen. Hier scheint es Schwankungen zu geben bzw. bei der Spannungsmessung daraus. . Macht es sich nur im Tool bemerkbar oder auch am Motor? Wie hoch sind diese Schwankungen? In wieweit sieht man die Schwwankugen aiuf dem OLED?
Die 0.5 Ohm sind es nicht.

**Comment by RollingGecko** [comment]
Please reopen if the problem still exists.
