### ISSUE TITLE
Wrong image in OLED memory?

### ISSUE THREAD

**Issue by Nohka** [RollingGecko/ArduBoardControler#4]
Hello!

I really like this open-source VESC-UART controller platform, great job, BUT I'd also like to get it working on my custom controller.. :/

The problem is that I got U8GLIB_SSD1306_ADAFRUIT_128X64 u8g(13, 11, 7, 6, 8); working with U8GLIB "GraphicsTest", but when I upload ArduBoardController_TX, it only shows a still image of the latest test screen it had in GraphicsTest.

I also have NRF24L01 connected to pins 9-13 accordingly.

What am I missing?

All the best!

**Comment by RollingGecko** [comment]
Sorry, but I have no possibility and resources at the moment to support in such problems. On the first look I would say, that the problem could be, that you use PIN 13 for the OLED and the NRF.

Please try other ports. Is there a problem to use the preconfigured ports?

**Comment by Nohka** [comment]
Indeed, that's what I'm doing. I will try other PIN, thanks! :)
